# action.yml
name: 'Deploy an application to AWS Elasticbeanstalk'
description: 'Deploy the application in your repository to AWS Elasticbeanstalk by using official client (eb-cli).'
inputs: 
    aws_access_key_id:
        description: 'AWS access key id'
        required: true
        default: '-'
    aws_secret_access_key:
        description: 'AWS secret access key'
        required: true
        default: '-'
outputs:
    deploymentoutput:
        description: 'The output from the deploy command (eb deploy)'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.aws_access_key_id }}
        - ${{ inputs.aws_secret_access_key }}